Omidiyeh Oil Company - 0147/Areas/Welfare/Controllers/SurveyController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MD.PersianDateTime;
using Omidiyeh_Oil_Company___0147.Implementations;
using Omidiyeh_Oil_Company___0147.Interfaces;
using Omidiyeh_Oil_Company___0147.Models;

namespace Omidiyeh_Oil_Company___0147.Areas.Welfare.Controllers
{
    public class SurveyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly dbEntities _db = new dbEntities();

        public SurveyController()
        {
            this._unitOfWork = new UnitOfWork<dbEntities>();
        }
        // GET: Welfare/Survey
        public ActionResult Index()
        {
            return View();
        }
        public  JsonResult QuestionItems(int survey=1)
        {

            var result = ( _unitOfWork.GetRepository<TblSurveyQuestion>().GetOrderedSyncNoTracking(
                a=>a.Survey == survey,orderBy: "Title", take: 1000, skip: 0));
            var (items, count, total) = result;
            return Json(items, JsonRequestBehavior.AllowGet);
        } 
        public  JsonResult SurveyItems()
        {

            var result = ( _unitOfWork.GetRepository<TblSurvey>().GetOrderedSyncNoTracking(
                orderBy: "Title", take: 1000, skip: 0));
            var (items, count, total) = result;
            return Json(items, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Responses()
        {
            return View();
        }

        public ActionResult ResponseList(SearchAdvancedTblSurveyResponse model)
        {
            Expression<Func<TblSurveyResponse, bool>> filter = (a) =>
                  //(model.Serving == null || a.Serving == model.Serving) &&
                  //(model.Type == null || a.TblFoodReservationGroup.Type == model.Type) &&
                  //(model.Confirm == null || a.TblFoodReservationGroup.Confirm == model.Confirm) &&
                  //(model.Group == 0 || a.Group == model.Group) &&
                  //(string.IsNullOrEmpty(model.UserName) || a.TblFoodReservationGroup.TblUser.UserName == model.UserName) &&
                  //(string.IsNullOrEmpty(model.Des) || a.TblFoodReservationGroup.Des.Contains(model.Des)) &&
                  //(string.IsNullOrEmpty(model.TblPerson.Name) || a.TblPerson.Name.Contains(model.TblPerson.Name)) &&
                  //(string.IsNullOrEmpty(model.TblPerson.Family) || a.TblPerson.Family.Contains(model.TblPerson.Family)) &&
                  //(string.IsNullOrEmpty(model.TblPerson.PersonnelCode) || a.TblPerson.PersonnelCode.Contains(model.TblPerson.PersonnelCode)) &&
                  //(string.IsNullOrEmpty(model.TblPerson.NationalCode) || a.TblPerson.NationalCode.Contains(model.TblPerson.NationalCode)) &&
                  //(string.IsNullOrEmpty(model.Des) || a.Des.Contains(model.Des)) &&
                  (model.Food.Contains(-5) || model.Food.Contains(a.Food)) &&
                  (model.Meal.Contains(-5) || model.Meal.Contains(a.Meal)) &&
                  (model.Restaurant.Contains(-5) || model.Restaurant.Contains(a.Restaurant)) &&
                  (model.Question.Contains(-5) || model.Question.Contains(a.Question)) &&
                  (model.Survey.Contains(-5) || model.Survey.Contains(a.Survey)) &&
                  (model.StartTime.Year == 1 || a.Time >= model.StartTime && a.Time <= model.EndTime) &&
                  (model.StartDate.Year == 1 || a.Date >= model.StartDate && a.Date <= model.EndDate) //&&

                  //(model.AccountNumber.Contains(0) || model.AccountNumber.Contains(a.TblFoodReservation.TblFoodReservationGroup.AccountNumber)) &&
                  //(model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.TblManagement.TblSubsidiary.Company == 0 || a.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.TblManagement.TblSubsidiary.Company == model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.TblManagement.TblSubsidiary.Company) &&
                  //(model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.TblManagement.Subsidiary == 0 || a.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.TblManagement.Subsidiary == model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.TblManagement.Subsidiary) &&
                  //(model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.Management == 0 || a.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.Management == model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.TblOffice.Management) &&
                  //(model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.Office == 0 || a.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.Office == model.TblFoodReservation.TblFoodReservationGroup.TblOfficeDepartmentAccountNumber.TblOfficeDepartment.Office) &&
                  //a.TblFoodReservation.TblFoodReservationGroup.Temp == false &&
                  //a.TblFoodReservation.TblFoodReservationGroup.Remove == false &&
                  //a.TblFoodReservation.Food != -1
          ;
            //Server Side Parameter
            var start = Convert.ToInt32(Request["start"]);
            var length = Convert.ToInt32(Request["length"]);
            // var searchValue = Request["search[value]"];
            var draw = Request["draw"];
            var order = "";
            foreach (var item in Request.Form.AllKeys.Where(a => a.StartsWith("order")))
            {
                if (item.EndsWith("[column]"))
                    order += Request["columns[" + Request[item] + "][name]"] + " ";
                else if (item.EndsWith("[dir]"))
                    order += Request[item] + ",";
            }
            length = length == 0 ? 100 : length;
            order = string.IsNullOrEmpty(order) ? "Id desc" : order.Substring(0, order.Length - 1);
            const string includeProperties = @"TblFoodReservation,
                                       TblRestaurant,TblFood,TblMeal,
                                        TblUser.TblPerson,
                                        TblSurveyQuestion.TblSurvey,
                                        TblSurveyQuestionOption,
                                       TblSurveyQuestion
                                        ";
            var iResult = _unitOfWork.GetRepository<TblSurveyResponse>();

            var result = iResult.GetOrderedSyncNoTracking(filter: filter,
                orderBy: order, take: length, skip: start, includeProperties: includeProperties);
            var (items, count, total) = result;

            var data = items?.Select(a => new
            {
                DT_RowId = a.Id,
                id = a.Id,
                TimeFa = new PersianDateTime(a.Time).ToString("yyyy/MM/dd HH:mm"),
                DateFa = new PersianDateTime(a.Date).ToString("yyyy/MM/dd"),
                a.Question,
                QuestionTitle= a.TblSurveyQuestion.Title,
                a.Option,
                OptionTitle = a.TblSurveyQuestionOption.Title,

                a.Survey,
                SurveyTitle = a.TblSurveyQuestion.TblSurvey.Title,

                a.Answer,
                a.FoodReservation,
                Person =    a.TblUser.TblPerson.Fullname(),
                RestaurantTitle=  a.TblRestaurant.Title,
                Restaurant= a.Restaurant,
                FoodTitle = a.TblFood.Title,
                Food = a.Food,
                a.Meal,
                MealTitle = a.TblMeal.Title,
                a.User,
                a.Time,
                
                
            }).ToList();
            var res = new
            {
                draw,
                recordsTotal = total.ToString(),
                recordsFiltered = count.ToString(),
                data
            };
            //return Json(res, JsonRequestBehavior.AllowGet);

            var jsonResult = Json(res, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public ActionResult Poll()
        {
            var s =  _unitOfWork.GetRepository<TblSurveyQuestion>().GetSync(a => a.Survey == 2 && a.Status, includeProperties: "TblSurveyQuestionOptions");

            return View(s);
        }
        public async Task<ActionResult> Poll2(int foodReservationId)
        {
            ViewBag.FoodReservationId = foodReservationId;
            var s = await _unitOfWork.GetRepository<TblSurveyQuestion>().Get(a => a.Survey == 1 && a.Status, includeProperties: "TblSurveyQuestionOptions");
            return PartialView(s);
        }

        [HttpPost]
        public JsonResult PollSave(int restaurants,int meals,int food, DateTime startDate)
        {
            var m = new Message();
          
            var user = Convert.ToInt32(User.Identity.Name);
            var list = new List<TblSurveyResponse>();
            foreach (var item in Request.Form.AllKeys.Where(a => a.StartsWith("Question")))
            {

                //Question-@(item.Id)
                var question = Convert.ToInt32(item.Split('-')[1]);
                var option = Convert.ToInt32(Request[item]);
                var answer = Request["Answer-" + question];
                var entity = new TblSurveyResponse
                {
                    Answer = answer,
                    FoodReservation = null,
                    Option = option,

Omidiyeh Oil Company - 0147/Areas/Welfare/Views/Survey/CreateOption.cshtml
<div class="modal fade rtl" id="modalOptionCreate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center py-3 grey lighten-5">
                <h6 class="modal-title w-100 font-weight-bold">ایجاد پاسخ برای @ViewBag.QuestionText</h6>

            </div>
            <div class="modal-body mx-3 ">
                <input type="hidden" value="@ViewBag.Question" name="QuestionForOptionCreate" id="QuestionForOptionCreate" />

                <div class="col-12">
                    <div class="md-form md-outline  my-0 input-group mr-auto  mt-1">
                        <input type="text" class="form-control text-center  validate" data-val-required=" " id="TitleOption" name="TitleOption" value="" required autocomplete="off">
                        <label for="TitleOption">پاسخ</label>
                        <div class="input-group-prepend cursor-pointer ">
                            <span class="input-group-text cursor-pointer" id="rdate"><i class="fas fa-question cursor-pointer"></i></span>
                        </div>
                    </div>
                </div>
                
            </div>


            <div class="modal-footer d-flex justify-content-center grey lighten-5">
                <button class="btn btn-link cta " type="submit" id="addOption" name="addOption" value="true" onclick="addOption();">
                    <i class="fas fa-save fa-lg"></i>
                    <span>ذخیره</span>
                </button>
            </div>
        </div>
    </div>
</div>

Omidiyeh Oil Company - 0147/Areas/Welfare/Views/Survey/CreateQuestion.cshtml
<div class="modal fade rtl" id="modalQuestionCreate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center py-3 grey lighten-5">
                <h4 class="modal-title w-100 font-weight-bold">ایجاد پرسش</h4>
            </div>
            <div class="modal-body mx-3 ">
                <div class="col-12">
                    <div class="md-form md-outline  my-0 input-group mr-auto  mt-1">
                        <input type="text" class="form-control text-center  validate" data-val-required=" " id="TitleQuestion" name="TitleQuestion" value="" required autocomplete="off">
                        <label for="TitleQuestion">پرسش</label>
                        <div class="input-group-prepend cursor-pointer ">
                            <span class="input-group-text cursor-pointer" id="rdate"><i class="fas fa-question cursor-pointer"></i></span>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-4">
                    <div class="col-12">
                        <div class="switch text-right">
                            <label class="">
                                <input type="checkbox" value="True" checked name="Anatomical" id="Anatomical">
                                <span class="lever"></span>
                               پاسخ تشریحی
                            </label>
                        </div>
                    </div>
                </div>
            <div class="col-12 mt-3">
                    <div class="col-12">
                        <div class="switch text-right">
                            <label class="">
                                <input type="checkbox" value="True" name="Necessary" id="Necessary">
                                <span class="lever"></span>
                               پاسخ به این پرسش الزامی می باشد
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-center grey lighten-5">
                <button class="btn btn-link cta " type="submit" id="addQuestion" name="addQuestion" value="true">
                    <i class="fas fa-save fa-lg"></i>
                    <span>ذخیره</span>
                </button>
            </div>
        </div>
    </div>
</div>

Omidiyeh Oil Company - 0147/Areas/Welfare/Views/Survey/Details.cshtml
@model Omidiyeh_Oil_Company___0147.Models.TblSurvey
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .mds-bootstrap-persian-datetime-picker-container {
        z-index: 1000;
    }
</style>
<div class="container px-0">
    <!-- Container -->
    <div class="row">
        <!-- Column -->
        <div class="col-md-4 mb-4 d-flex align-items-stretch">
            <div class="card col-12">
                <div class="card-body">
                    <div id="date6"></div>
                </div>
            </div>
        </div>
        <!-- Column -->
        <!-- Column -->
        <div class="col-md-4 mb-4 d-flex align-items-stretch">
            <!--Card-->
            <div class="card col-12">
                <!--Card content-->
                <div class="card-body text-right">
                  
                    
                    <!--Text-->
                   
                        <a href="/Welfare/Survey/Responses" class=" mb-4">
                            نتایج نظرسنجی
                        </a>
                  

                </div>
            </div>
            <!--/.Card-->
        </div>
        <!-- Column -->
        <!-- Column -->
        <div class="col-md-4 mb-4 d-flex align-items-stretch">
            <!--Card-->
            <div class="card testimonial-card col-12 px-0">
                <!-- Background color -->
                <div class="card-up aqua-gradient"></div>
                <!-- Avatar -->
                <div class="avatar mx-auto white">
                    <img src="~/Images/survey.jpg" class="rounded-circle img-responsive" alt="avatar">
                </div>
                <!-- Content -->
                <div class="card-body">
                    <!-- Name -->
                    <h4 class="card-title font-weight-bold">@Model.Title</h4>
                    <hr>
                    <a href="" class=" mb-4" data-toggle="modal" data-target="#modalQuestionCreate">
                        ایجاد پرسش
                    </a>
                </div>
            </div>
            <!--Card-->
        </div>
        <!-- Column -->
    </div>
    <hr />
    <div id="questions" class="row">

    </div>

</div>
@Html.Action("CreateQuestion", "Survey")
<div id="createOption" class="row"></div>
<div id="responseOption" class="row"></div>
<div id="editQuestion" class="row"></div>
<div id="editOption" class="row"></div>
@section scripts{
    <script>
        $('[data-toggle="popover"]').popover({
            trigger: 'hover',
            container: 'body',
        });
        //console.log(1);
        $('#date6').MdPersianDateTimePicker({
            inLine: true,
            enableTimePicker: true
        });
        $('.grid').masonry({
            itemSelector: '.grid-item',
            columnWidth: '.grid-sizer',
            percentPosition: true,
            isRTL: true,
            isOriginLeft: false
        });

        function createOption(question, text) {
            $.ajax({
                url: "/Welfare/Survey/CreateOption",
                data: { question: question, text: text },
                type: 'GET',
                success: function(data) {
                    $('#createOption').html(data);
                    $('#modalOptionCreate').modal('show');
                },
                error: function(data) {
                    toastr["error"](`هنگام انجام درخواست شما  خطایی رخ داده است.<br /><small>${data}</small>`);
                }
            }).then(function() {});
        }

        function responseOption(question, text) {
            $.ajax({
                url: "/Welfare/Survey/ResponseOption",
                data: { question: question, text: text },
                type: 'GET',
                success: function(data) {
                    $('#responseOption').html(data);
                    $('#modalOptionResponse').modal('show');
                },
                error: function(data) {
                    toastr["error"](`هنگام انجام درخواست شما  خطایی رخ داده است.<br /><small>${data}</small>`);
                }
            }).then(function() {});
        }


        

        function addOption(e) {

            $.ajax({
                url: "/Welfare/Survey/CreateOption",
                data: {
                    question: $('#QuestionForOptionCreate').val(),
                    title: $('#TitleOption').val(),
                    text: 'پاسخ'
                },
                type: 'POST',
                success: function(data) {
                    //  toastr[data.Type](data.Msg);
                    toastr[data.Type](data.Msg);
                    if (data.Result === true)
                        loadQuestions();
                    $('#TitleOption').val('');

                    $('#modalOptionCreate').modal('hide');
                }
            });
        };
      
        function deleteOption(id) {
            $.ajax({
                url: "/Welfare/Survey/deleteOption",
                data: { id: id },
                type: 'GET',
                success: function(data) {
                    toastr[data.Type](data.Msg);
                    if (data.Result === true)
                        loadQuestions();
                    $('#modalOptionEdit').modal('hide');
                },
                error: function(data) {

                    toastr["error"](`هنگام انجام درخواست شما  خطایی رخ داده است.<br /><small>${data}</small>`);
                }
            }).then(function() {

            });
        }
        function editOption(id) {
            $.ajax({
                url: "/Welfare/Survey/EditOption",
                data: { id: id},
                type: 'GET',
                success: function(data) {
                    $('#editOption').html(data);
                    $('#modalOptionEdit').modal('show');
                },
                error: function(data) {

                    toastr["error"](`هنگام انجام درخواست شما  خطایی رخ داده است.<br /><small>${data}</small>`);
                }
            }).then(function() {

            });
        }
        function editOptionSave () {
            const status = $('#modalOptionEdit #Status').is(':checked') ? true : false;
            $.ajax({
                url: "/Welfare/Survey/EditOption/",
                data: {
                    title: $('#modalOptionEdit #TitleOption').val(),
                    status: status,
                    id: $('#modalOptionEdit #Id').val()
                },
                type: 'POST',
                success: function(data) {
                    toastr[data.Type](data.Msg);
                    if (data.Result === true)
                        loadQuestions();
                    $('#modalOptionEdit').modal('hide');
                }
            });
        }

        function loadQuestions() {
            $.ajax({
                url: "/Welfare/Survey/Questions/",
                data: { id: @Model.Id },
                type: 'GET',
                success: function(data) {
                    $('#questions').html(data);
                },
                error: function(data) {

                    toastr["error"](`هنگام انجام درخواست شما  خطایی رخ داده است.<br /><small>${data}</small>`);
                }
            }).then();
        }


            
         $('#addQuestion').on('click',
            function (e) {
                //e.preventDefault();
                const anatomical = $('#modalQuestionCreate #Anatomical').is(':checked') ? true : false;
                const necessary = $('#modalQuestionCreate #Necessary').is(':checked') ? true : false;

                $.ajax({
                    url: "/Welfare/Survey/CreateQuestion/",
                    data: {
                        title: $('#modalQuestionCreate #TitleQuestion').val(),
                        anatomical: anatomical,
                        necessary: necessary,
                        survey: @Model.Id
                    },
                    type: 'POST',
                    success: function(data) {
                        //  toastr[data.Type](data.Msg);
                        toastr[data.Type](data.Msg);
                        if (data.Result === true)
                            loadQuestions();
                        $('#TitleQuestion').val('');

                        $('#modalQuestionCreate').modal('hide');
                    }
                });
             });

       
        function deleteQuestion(id) {
            $.ajax({
                url: "/Welfare/Survey/DeleteQuestion",
                data: { id: id },
                type: 'GET',
                success: function(data) {
                    toastr[data.Type](data.Msg);
                    if (data.Result === true)
                        loadQuestions();
                    $('#modalQuestionEdit').modal('hide');

                },
                error: function(data) {

                    toastr["error"](`هنگام انجام درخواست شما  خطایی رخ داده است.<br /><small>${data}</small>`);
                }
            }).then(function() {

            });
        }
        function editQuestion(id) {
            $.ajax({
                url: "/Welfare/Survey/EditQuestion",
                data: { id: id},
                type: 'GET',
                success: function(data) {
                    $('#editQuestion').html(data);
                    $('#modalQuestionEdit').modal('show');
                },
                error: function(data) {

                    toastr["error"](`هنگام انجام درخواست شما  خطایی رخ داده است.<br /><small>${data}</small>`);
                }
            }).then(function() {

            });
        }
        function editQuestionSave () {
            // e.preventDefault();
            const anatomical = $('#modalQuestionEdit #Anatomical').is(':checked') ? true : false;
            const necessary = $('#modalQuestionEdit #Necessary').is(':checked') ? true : false;
            const status = $('#modalQuestionEdit #Status').is(':checked') ? true : false;

            $.ajax({
                url: "/Welfare/Survey/EditQuestion/",
                data: {
                    title: $('#modalQuestionEdit #TitleQuestion').val(),
                    anatomical: anatomical,
                    necessary: necessary,
                    status: status,
                    id: $('#modalQuestionEdit #Id').val()
                },
                type: 'POST',
                success: function(data) {
                    //  toastr[data.Type](data.Msg);
                    toastr[data.Type](data.Msg);
                    if (data.Result === true)
                        loadQuestions();
                    // $('#TitleQuestion').val('');

                    $('#modalQuestionEdit').modal('hide');
                }
            });
        }

        $(document).ready(function() {
            loadQuestions();
        });
    </script>
}

Omidiyeh Oil Company - 0147/Areas/Welfare/Views/Survey/EditOption.cshtml
@model Omidiyeh_Oil_Company___0147.Models.TblSurveyQuestionOption

<div class="modal fade rtl" id="modalOptionEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center py-3 grey lighten-5">
                <h4 class="modal-title w-100 font-weight-bold">ویرایش پاسخ</h4>
            </div>
            <div class="modal-body mx-3 ">
                <div class="col-12">
                    <div class="md-form md-outline  my-0 input-group mr-auto  mt-1">
                        <input type="text" class="form-control text-center  validate" data-val-required=" " id="TitleOption" name="TitleOption" value="@Model.Title" required autocomplete="off">
                        <label for="TitleOption">پاسخ</label>
                        <div class="input-group-prepend cursor-pointer ">
                            <span class="input-group-text cursor-pointer" id="rdate"><i class="fas fa-question cursor-pointer"></i></span>
                        </div>
                    </div>
                </div>
                
                
                <div class="col-12 mt-3">
                    <div class="col-12">
                        <div class="switch text-right">
                            <label class="">
                                <input type="checkbox" value="True" @(Model.Status ? "checked" : "") name="Status" id="Status">
                                <span class="lever"></span>
                                فعال
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-center grey lighten-5">
                <input type="hidden" name="Id" id="Id" value="@Model.Id" />
                <button class="btn btn-link cta " type="button" value="true" onclick="editOptionSave()">
                    <i class="fas fa-save fa-lg"></i>
                    <span>ذخیره</span>
                </button>
                <button class="btn btn-link cta cta-silver" type="button" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-save fa-lg"></i>
                    <span>انصراف</span>
                </button>
                <button class="btn btn-link cta cta-red " type="button" onclick="deleteOption(@Model.Id)">
                    <i class="fas fa-save fa-lg"></i>
                    <span>حذف </span>
                </button>
            </div>

        </div>
    </div>
</div>

Omidiyeh Oil Company - 0147/Areas/Welfare/Views/Survey/EditQuestion.cshtml
@model Omidiyeh_Oil_Company___0147.Models.TblSurveyQuestion

<div class="modal fade rtl" id="modalQuestionEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center py-3 grey lighten-5">
                <h4 class="modal-title w-100 font-weight-bold">ویرایش پرسش</h4>
            </div>
            <div class="modal-body mx-3 ">
                <div class="col-12">
                    <div class="md-form md-outline  my-0 input-group mr-auto  mt-1">
                        <input type="text" class="form-control text-center  validate" data-val-required=" " id="TitleQuestion" name="TitleQuestion" value="@Model.Title" required autocomplete="off">
                        <label for="TitleQuestion">پرسش</label>
                        <div class="input-group-prepend cursor-pointer ">
                            <span class="input-group-text cursor-pointer" id="rdate"><i class="fas fa-question cursor-pointer"></i></span>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-4">
                    <div class="col-12">
                        <div class="switch text-right">
                            <label class="">
                                <input type="checkbox" value="True" @(Model.Anatomical? "checked" : "")  name="Anatomical" id="Anatomical">
                                <span class="lever"></span>
                                پاسخ تشریحی
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <div class="col-12">
                        <div class="switch text-right">
                            <label class="">
                                <input type="checkbox" value="True"  @(Model.Necessary? "checked" : "")  name="Necessary" id="Necessary">
                                <span class="lever"></span>
                                پاسخ به این پرسش الزامی می باشد
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <div class="col-12">
                        <div class="switch text-right">
                            <label class="">
                                <input type="checkbox" value="True"  @(Model.Status? "checked" : "")  name="Status" id="Status">
                                <span class="lever"></span>
                               فعال
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-center grey lighten-5">
                <input type="hidden" name="Id" id="Id" value="@Model.Id" />
                <button class="btn btn-link cta " type="button" value="true" onclick="editQuestionSave()">
                    <i class="fas fa-save fa-lg"></i>
                    <span>ذخیره</span>
                </button>
                <button class="btn btn-link cta cta-silver" type="button" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times fa-lg"></i>
                    <span>انصراف</span>
                </button>
                <button class="btn btn-link cta cta-red " type="button" onclick="deleteQuestion(@Model.Id)">
                    <i class="fas fa-trash-alt fa-lg"></i>
                    <span>حذف </span>
                </button>
            </div>
            
        </div>
    </div>
</div>